apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-learning-platform
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ai-learning-platform
  template:
    metadata:
      labels:
        app: ai-learning-platform
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000