apiVersion: v1
kind: Service
metadata:
  name: ai-learning-service
spec:
  type: NodePort
  selector:
    app: ai-learning-platform
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007