apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: housing
  template:
    metadata:
      labels:
        app: housing
    spec:
      containers:
      - name: housing
        image: pranil0712/housing-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: housing-service
spec:
  type: NodePort
  selector:
    app: housing
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005