apiVersion: v1
kind: Service
metadata:
  name: ai-learning-platform
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ai-learning-platform
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}